
name: run unittest on project

on:

  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]



jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Run unittests
        run: py -m unittest rectangle.py circle.py square.py triangle.py
